# Generated by Django 5.2.1 on 2025-06-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_date_joined_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(default='Fixed Term', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='Unknown Name', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='Unknown Title', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='point_of_hire',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Unknown Department', max_length=100),
        ),
    ]
