# Generated by Django 5.2.1 on 2025-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_date_joined_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_period_months',
            field=models.PositiveIntegerField(blank=True, help_text='Contract period in months (for non-permanent)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Fixed Term', 'Fixed Term'), ('Short Term', 'Short Term'), ('Intern', 'Intern'), ('Probation', 'Probation'), ('Verbal', 'Verbal'), ('Consultant', 'Consultant'), ('Temporary', 'Temporary'), ('Seasonal', 'Seasonal'), ('Apprentice', 'Apprentice'), ('Other', 'Other')], default='Fixed Term', max_length=50),
        ),
    ]
