# Generated by Django 5.2.1 on 2025-06-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritytorecruit',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Maintenance', 'Maintenance'), ('Ops', 'Operations'), ('Stores', 'SupplyChain')], max_length=50),
        ),
    ]
