# Generated by Django 5.2.1 on 2025-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_authoritytorecruit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='background_check_status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='drug_test_result',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='onboarding_completed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='applicant',
            name='physical_fitness_test',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='psychological_evaluation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='qualifications_met',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screening_notes',
            field=models.TextField(blank=True),
        ),
    ]
