# Generated by Django 5.2.1 on 2025-06-26 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_date_joined_remove_employee_email_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancereview',
            options={},
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='score',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='adaptability_flexibility',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='attendance_punctuality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='communication_skills',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='goals_met',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='initiative_problem_solving',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='job_knowledge',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewed_by',
            field=models.CharField(default='Supervisor', max_length=100),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='safety_compliance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='supervisor_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='teamwork_collaboration',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='work_quality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
